import "./globals.css";
import {Roboto} from "next/font/google";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ['300','400','500'],
    variable: '--font-Roboto'
})
export const metadata = {
    title: 'FenrirTestLand',
    description: 'Generated by create next app',
    icon: '/favicon.ico'
};

export default function RootLayout({ children }) {
    return (
        <html lang= 'en'>
        <body className = {`${roboto.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}
